<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <RootNamespace>AvaloniaUI.Ribbon</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Version>0.9.9</Version>
        <Authors>Splitwirez, Alban Mazerolles, Rubal Walia, Sachith Liyanagama</Authors>
        <PackageId>AvaloniaControls.Ribbon</PackageId>
        <PackageProjectUrl>https://github.com/SachiHarshitha/Avalonia.Ribbon</PackageProjectUrl>
        <Description>Office-Like ribbon control for Avalonia framework, for cross-platform projects such as WASM and Desktop.</Description>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/SachiHarshitha/Avalonia.Ribbon.git</RepositoryUrl>
        <AssemblyName>AvaloniaUI.Ribbon</AssemblyName>
        <LangVersion>latest</LangVersion>
        <PackageTags>ribbon;avalonia;avaloniaui;avalonia ui;ribbon;ribbonui;ribbon ui;crossplat;crossplatform;cross platform;xplat;xplatform;wasm</PackageTags>
        <Title>Cross-Platform Ribbon control for Avalonia</Title>
        <Copyright>Partial Copyright (c) 2023 Sachith Liyanagama</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <!--owners? requireLicenseAcceptance? releaseNotes? copyright?-->
    </PropertyGroup>
    <ItemGroup>
        <Compile Update="**\*.axaml.cs">
            <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <AvaloniaResource Include="**\*.axaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    <ItemGroup>
      <AvaloniaXaml Remove="Styles\Fluent\Controls\RibbonDropDownItemsPresenter.axaml" />
    </ItemGroup>
    <ItemGroup>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.9" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
        <PackageReference Include="System.Text.Json" Version="10.0.0" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="11.3.9" />
    </ItemGroup>
</Project>